name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Minilla
        uses: Songmu/setup-minil@0d5985b33eb9dd718dd6c416f6c801b884fcb672 # v0.0.4
      - name: Build distribution
        id: dist
        run: |
          output="$(minil dist --skip-prepare --no-test)"
          echo "$output"
          dist="$(tail -n 1 <<<"$output" | jq -er '.dist')"
          printf 'dist=%s\n' "$dist" >>"$GITHUB_OUTPUT"
      - name: Upload distribution to PAUSE
        uses: skaji/action-pause-upload@5a97e01abbc706d80964d6ea1e52c43293b4d8a5 # v1.0.0
        with:
          files: ${{ steps.dist.outputs.dist }}
          pause-token: ${{ secrets.PAUSE_TOKEN }}
